### ISSUE TITLE
image captioning task

### ISSUE THREAD

**Issue by upccpu** [peteanderson80/bottom-up-attention#11] opened 2017-10-15 11:47 UTC
hi, peteanderson:
        I have paid close attention to you for a long time in the Cross-modal field. And, your bottom-up& top-down work really made greatly improved than other works. According to your paper, i accomplished the top-down algorithm for image captioning. But i could not reproduce your 'CIDER loss'. So i just use the 'cross entropy loss' . If possible, i hope you will put your image captioning code on github.
      Wish you will rollout another wonderful article in CVPR 2018.

**Comment by peteanderson80** [comment] 2017-10-19 02:37
Closing as a duplicate of https://github.com/peteanderson80/bottom-up-attention/issues/9. We will try to get the captioning model code released.

**Closed by peteanderson80** 2017-10-19 02:37 UTC
